export const SCENE_VIEWER_BACKGROUND_COLOR = 0xAAAAAA

export const SCENE_OBJECT_HOVER_COLOR = 0x6dd5ed

export const SCENE_PLANE_COLOR = 0x2193b0
export const SCENE_PLANE_LENGTH = 3
export const SCENE_PLANE_OPACITY = 0.6

export const AXES_HELPER_LENGTH = 5
